"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.core.management.commands.runserver import Command as runserver
runserver.default_port = "5005"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
load_dotenv(dotenv_path=".env.local", override=True)
SECRET_KEY = os.getenv("DJANGO_SECRET")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # Ensure 'backend' is listed after the default apps
    'backend',
    'djangocms_admin_style',
    'django_nextjs',
    'cms',
    'corsheaders',
    'rest_framework',
    'menus',
    'treebeard', 
    'sekizai', 
    'filer',
    'easy_thumbnails',
    'mptt',
    'djangocms_text_ckeditor',
    'djangocms_link',
    'djangocms_file',
    'djangocms_picture',
    'djangocms_video',
    'djangocms_googlemap',
    'djangocms_snippet',
    'djangocms_style',
    'djangocms_column',
    'django_cleanup.apps.CleanupConfig',
    'csp',
]

# AUTH_USER_MODEL = 'backend.User'

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'django.middleware.locale.LocaleMiddleware', 
    'cms.middleware.utils.ApphookReloadMiddleware',
    'cms.middleware.user.CurrentUserMiddleware',
    'cms.middleware.page.CurrentPageMiddleware',
    'cms.middleware.toolbar.ToolbarMiddleware',
    'cms.middleware.language.LanguageCookieMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'csp.middleware.CSPMiddleware',
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.i18n",
                'sekizai.context_processors.sekizai',
                'cms.context_processors.cms_settings',
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": f"{BASE_DIR}/db.sqlite3",
    }
}

MEDIA_ROOT = os.path.join(BASE_DIR, 'master')
MEDIA_URL = '/master/'

THUMBNAIL_HIGH_RESOLUTION = True

THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters'
)

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

SITE_ID = 1
LANGUAGES = [
    ('en-us', 'English (US)'),
    # ('zh', u'中文'),
]

TIME_ZONE = "Asia/Taipei"

USE_I18N = True

USE_TZ = False

CMS_CONFIRM_VERSION4 = True

# CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOWED_ORIGINS = [
    'http://localhost:5003',
    'http://192.168.50.26:5003',
    'http://192.168.50.36:5003',
    'https://learn.residemy.org',
    'https://admin.learn.residemy.org',
    'https://stage-learn.residemy.org',
]

ALLOWED_HOSTS = [
    '192.168.50.26', 
    '192.168.50.36',
    '127.0.0.1', 
    '0.0.0.0', 
    'localhost',
    '140.114.135.90', 
    'learn.residemy.org', 
    'admin.learn.residemy.org', 
    'stage-learn.residemy.org',
]

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5003',
    'https://learn.residemy.org', 
    'https://admin.learn.residemy.org', 
    'https://stage-learn.residemy.org',
]

# CORS_ALLOW_HEADERS = [
#     'X-Frame-Options',
# ]

# CORS_EXPOSE_HEADERS = [
#     'X-Frame-Options',
# ]

# X_FRAME_OPTIONS = 'ALLOW-FROM https://admin.learn.residemy.org/'


CSP_FRAME_ANCESTORS = [
    "'self'", 
    "https://stage-learn.residemy.org/",
    "http://localhost:5003/",
]

CSP_DEFAULT_SRC = ("'self'",)
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'")
CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'")

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

load_dotenv(dotenv_path='.env.local')
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

# Maximum size (in bytes) that a request body may be
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600000  # 100 MB (adjust as needed)

# Maximum size (in bytes) that an uploaded file may be
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600000  # 100 MB (adjust as needed)