# Generated by Django 4.2.7 on 2024-02-07 16:28

import backend.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forumdocument",
            name="document",
            field=models.FileField(
                help_text="Only PDF Allowed.",
                upload_to=backend.models.document_directory_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "ppt", "pptx"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="forumdocument",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Leave blank to use filename as title.",
                max_length=255,
            ),
        ),
    ]
