# Generated by Django 4.2.7 on 2024-02-07 16:43

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_alter_forumdocument_document_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="forumdocument",
            name="snapshot",
            field=models.ImageField(
                blank=True, null=True, upload_to=backend.models.snapshot_directory_path
            ),
        ),
    ]
