# Generated by Django 4.2.7 on 2024-02-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_forumdocument_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="forum",
            name="upload_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="forumdocument",
            name="upload_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
