# Generated by Django 4.2.7 on 2024-02-17 16:42

import backend.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_forum_upload_time_forumdocument_upload_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="forum",
            name="click_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="forumdocument",
            name="click_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="forum",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="forumdocument",
            name="document",
            field=models.FileField(
                help_text="Only PDF Allowed.",
                upload_to=backend.models.document_directory_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
    ]
